# Generated by Django 4.2 on 2023-05-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.timestamp')),
                ('title', models.CharField(max_length=225)),
            ],
            bases=('main.timestamp',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.timestamp')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(blank=True, max_length=225, null=True)),
                ('subject', models.CharField(blank=True, max_length=225, null=True)),
                ('message', models.TextField()),
            ],
            bases=('main.timestamp',),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.timestamp')),
                ('email', models.EmailField(db_index=True, max_length=225, unique=True)),
            ],
            bases=('main.timestamp',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.timestamp')),
                ('title', models.CharField(max_length=225)),
            ],
            bases=('main.timestamp',),
        ),
    ]
